<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-09-18T12:10:50+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      calendar.summary_thumbnail_attribute
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '9.0.0RC4',
    'version_db_installed' => '20210910234801',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1629458287,
        'latest_version' => '9.0.0RC4',
    ],
    'seo' => [
        'redirect_to_canonical_url' => false,
        'url_rewriting' => true,
    ],
    'permissions' => [
        'model' => 'advanced',
    ],
    'calendar' => [
        'topic_attribute' => '',
        'summary_thumbnail_attribute' => '',
    ],
];
