<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-09-10T15:16:36+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      permissions.model
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '9.0.0RC3',
    'version_db_installed' => '20210813173441',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1629458287,
        'latest_version' => '9.0.0RC3',
    ],
    'seo' => [
        'redirect_to_canonical_url' => false,
        'url_rewriting' => true,
    ],
    'permissions' => [
        'model' => 'advanced',
    ],
];
